name: Mobile Test Automation

on:
  workflow_dispatch:

jobs:
  Main:
    uses: intive/patronage22_mobile_auto_szczecin/.github/workflows/main-template.yml@main
    with:
      BUILD: Main Automation
      NAME: Test Mobile on Samsung
      RUN: mvn clean test -Ddevice="bs_samsung" -Dbrowserstack="True"
    secrets:
      BROWSERSTACK_USER: ${{ secrets.BROWSERSTACK_USER }}
      BROWSERSTACK_KEY: ${{ secrets.BROWSERSTACK_KEY }}


