name: Reusable workflow for web test automation

on:
  workflow_call:
    inputs:
      BUILD:
        required: true
        type: string
      NAME:
        required: true
        type: string
      RUN:
        required: true
        type: string
    secrets:
      BROWSERSTACK_USER:
        required: true
      BROWSERSTACK_KEY:
        required: true

jobs:
  WebTest:
    runs-on: ubuntu-20.04
    env:
      BROWSERSTACK_USER: ${{secrets.BROWSERSTACK_USER}}
      BROWSERSTACK_KEY: ${{secrets.BROWSERSTACK_KEY}}
      BUILD: ${{inputs.BUILD}}

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: ${{inputs.NAME}}
        run: ${{inputs.RUN}}
      - name: Add Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: reports
          path: target/
